services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=developmentsk
      - POSTGRES_DB=shokanri
      - POSTGRES_USER=developmentsk
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: